# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\.git\vscode\yundongyuanguanlixitong\change.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change(object):
    def setupUi(self, Change):
        Change.setObjectName("Change")
        Change.resize(365, 139)
        self.comboBox = QtWidgets.QComboBox(Change)
        self.comboBox.setGeometry(QtCore.QRect(70, 50, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Change)
        self.label.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Change)
        self.lineEdit.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Change)
        self.pushButton.setGeometry(QtCore.QRect(260, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Change)
        QtCore.QMetaObject.connectSlotsByName(Change)

    def retranslateUi(self, Change):
        _translate = QtCore.QCoreApplication.translate
        Change.setWindowTitle(_translate("Change", "Dialog"))
        self.label.setText(_translate("Change", "项目："))
        self.pushButton.setText(_translate("Change", "确认"))
