'''
Author: your name
Date: 2021-01-30 02:46:30
LastEditTime: 2021-01-30 03:13:25
LastEditors: your name
Description: In User Settings Edit
FilePath: \Desktopd:\.git\vscode\yundongyuanguanlixitong\Ui_playertype.py
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\.git\vscode\yundongyuanguanlixitong\playertype.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerType(object):
    def setupUi(self, PlayerType):
        PlayerType.setObjectName("PlayerType")
        PlayerType.resize(360, 196)
        self.pushButton = QtWidgets.QPushButton(PlayerType)
        self.pushButton.setGeometry(QtCore.QRect(60, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(PlayerType)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 130, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(PlayerType)
        self.label.setGeometry(QtCore.QRect(70, 30, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(PlayerType)
        QtCore.QMetaObject.connectSlotsByName(PlayerType)

    def retranslateUi(self, PlayerType):
        _translate = QtCore.QCoreApplication.translate
        PlayerType.setWindowTitle(_translate("PlayerType", "Dialog"))
        self.pushButton.setText(_translate("PlayerType", "球员"))
        self.pushButton_2.setText(_translate("PlayerType", "守门员"))
        self.label.setText(_translate("PlayerType", "球员身份"))
