# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\.git\vscode\yundongyuanguanlixitong\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPassword(object):
    def setupUi(self, ResetPassword):
        ResetPassword.setObjectName("ResetPassword")
        ResetPassword.resize(389, 171)
        self.lineEdit = QtWidgets.QLineEdit(ResetPassword)
        self.lineEdit.setGeometry(QtCore.QRect(110, 80, 161, 21))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(ResetPassword)
        self.label.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(ResetPassword)
        self.pushButton.setGeometry(QtCore.QRect(280, 80, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ResetPassword)
        QtCore.QMetaObject.connectSlotsByName(ResetPassword)

    def retranslateUi(self, ResetPassword):
        _translate = QtCore.QCoreApplication.translate
        ResetPassword.setWindowTitle(_translate("ResetPassword", "重置密码"))
        self.label.setText(_translate("ResetPassword", "请输入新密码："))
        self.pushButton.setText(_translate("ResetPassword", "确定"))
